export const ACTIVE_ROLE_OPTIONS = [
  { name: "Automation Intern", code: "AUT" },
  { name: "Full Stack Developer Intern", code: "FSD" },
  { name: "Java Developer Intern", code: "JAV" },
  { name: "Project Manager Intern", code: "PMT" },
  { name: "Clinical Psychologist Intern", code: "CPS" },
  { name: "Psycho-Oncology Support Intern", code: "POS" },
  { name: "Clinical Dietitian Intern", code: "CDT" },
  { name: "Nutritionist Intern", code: "NUT" },
  { name: "HR Psyconnect Intern", code: "HPI" },
  { name: "HR Operations Intern", code: "HRO" },
  { name: "Talent Acquisition Intern", code: "TAC" },
  { name: "Business Development Intern", code: "BDE" },
  { name: "Graphic Designer Intern", code: "GDS" },
  { name: "Poster Designer Intern", code: "PDS" },
  { name: "Video Editor Intern", code: "VED" },
  { name: "Public Relations Intern", code: "PRL" },
  { name: "Social Media Manager Intern", code: "SMM" },
  { name: "Operations Associate Intern", code: "OPA" },
  { name: "UI/UX Designer Intern", code: "UIX" },
  { name: "Marketing Intern", code: "MKT" },
  { name: "Lead Generation Intern", code: "LGE" },
];

export const LEGACY_LIFECYCLE_ROLE_CODES = [
  "AOP",
  "BAI",
  "CON",
  "DAT",
  "DES",
  "FIN",
  "HRI",
  "HPS",
  "HPI",
  "LGE",
  "MKT",
  "MOG",
  "OPR",
  "PRD",
  "PYA",
  "QAI",
  "RES",
  "SAM",
  "SMM",
  "SUP",
  "SWI",
];

export const LIFECYCLE_SUPPORTED_ROLE_CODES = [
  ...new Set([
    ...ACTIVE_ROLE_OPTIONS.map((role) => role.code),
    ...LEGACY_LIFECYCLE_ROLE_CODES,
  ]),
];
