export const ROLE_OPTIONS = [
  { name: "Business Analyst Intern", code: "BAI" },
  { name: "Content Intern", code: "CON" },
  { name: "Data Intern", code: "DAT" },
  { name: "Design Intern", code: "DES" },
  { name: "Finance Intern", code: "FIN" },
  { name: "HR Intern", code: "HRI" },
  { name: "HR Psyconnect Intern", code: "HPI" },
  { name: "Marketing Intern", code: "MKT" },
  { name: "Operation Intern", code: "OPR" },
  { name: "Product Intern", code: "PRD" },
  { name: "QA Intern", code: "QAI" },
  { name: "Research Intern", code: "RES" },
  { name: "Software Intern", code: "SWI" },
  { name: "Support Intern", code: "SUP" },
];
