export const ROLE_OPTIONS = [
  { name: "Automation & Operations", code: "AOP" },
  { name: "Brand Management & Outreach", code: "BMO" },
  { name: "Business Development", code: "BDE" },
  { name: "Clinical Psychologist", code: "CPS" },
  { name: "Content Creation", code: "CON" },
  { name: "Creative Design", code: "CRD" },
  { name: "Graphic Design", code: "GDE" },
  { name: "HR Psychologist", code: "HPS" },
  { name: "Human Resources (HR)", code: "HRM" },
  { name: "Lead Generation", code: "LGE" },
  { name: "Marketing", code: "MKT" },
  { name: "Media & Public Relations (PR)", code: "MPR" },
  { name: "Motion Graphics", code: "MOG" },
  { name: "Operations", code: "OPR" },
  { name: "Project Management", code: "PMT" },
  { name: "Python Automation", code: "PYA" },
  { name: "Sales and Marketing", code: "SAM" },
  { name: "Social Media Management", code: "SMM" },
  { name: "Talent Acquisition", code: "TAC" },
  { name: "Video Editing/Making", code: "VEM" },
  { name: "UI/UX Design", code: "UIX" },
  { name: "Full stack Developer", code: "FSD" },
];
